services:
  nginx:
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nginx/ssl.crt:/etc/nginx/ssl/ssl.crt:ro
      - ./volumes/nginx/ssl.key:/etc/nginx/ssl/ssl.key:ro

  client:
    build:
      dockerfile: Dockerfile.development
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/client:/app
      - /app/node_modules

  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    environment:
      ### Shared ###
      # Debugging
      - DEBUG_MODE=false
      - DEBUG_MODE_ATTACH_PROCESS_WAITING_PERIOD_SECONDS=60
    volumes:
      ### Shared ###
      # Allow source code file watching
      - ./backend/Shared:/src/Shared:delegated
      # Use development volumes
      - ./volumes/backend/shared/data-protection:/app/shared/data-protection:ro
      - ./volumes/backend/shared/authentication:/app/shared/authentication:ro
      # Improve performance and allow hot reloading
      - /src/Shared/obj
      - /src/Shared/bin
      ### API ###
      # Allow source code file watching
      - ./backend/Api:/src/Api:delegated
      # Improve performance and allow hot reloading
      - /src/Api/obj
      - /src/Api/bin
      ### Accounts ###
      # Allow source code file watching
      - ./backend/Accounts:/src/Accounts:delegated
      # Use development volumes
      - ./volumes/backend/accounts:/app/accounts:ro
      # Improve performance and allow hot reloading
      - /src/Accounts/Accounts/obj
      - /src/Accounts/Accounts/bin
      - /src/Accounts/Accounts.Contracts/obj
      - /src/Accounts/Accounts.Contracts/bin
      - /src/Accounts/Accounts.Tests/obj
      - /src/Accounts/Accounts.Tests/bin
