services:
  nginx:
    volumes:
      - ./docker-dev-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-dev-volumes/nginx/ssl/ssl.crt:/etc/nginx/ssl/ssl.crt:ro
      - ./docker-dev-volumes/nginx/ssl/ssl.key:/etc/nginx/ssl/ssl.key:ro

  client:
    build:
      dockerfile: Dockerfile.development
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/client:/app
      - /app/node_modules

  api:
    build:
      dockerfile: Api/Dockerfile.development
    restart: on-failure
    environment:
      - DEBUG_MODE
      - DEBUG_MODE_ATTACH_PROCESS_WAITING_PERIOD_SECONDS=60
    volumes:
      # Use development data protection certificates
      - ./docker-dev-volumes/backend/shared/data-protection/certificates:/app/certificates:ro
      # Enable dotnet file watch and hot reloading
      - ./backend:/src:delegated
      # API
      - /src/Api/obj
      - /src/Api/bin
      # Shared
      - /src/Shared/obj
      - /src/Shared/bin
      # Accounts
      - /src/Accounts/Accounts/obj
      - /src/Accounts/Accounts/bin
      - /src/Accounts/Accounts.Contracts/obj
      - /src/Accounts/Accounts.Contracts/bin
      - /src/Accounts/Accounts.Tests/obj
      - /src/Accounts/Accounts.Tests/bin