services:
  nginx:
    image: nginx:1.25.3
    container_name: modmontemplate-nginx
    restart: unless-stopped
    ports:
      - "49152:80"
      - "49153:443"
    depends_on:
      client:
        condition: service_started
      api:
        condition: service_started
    volumes:
      - ${VOLUMES_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${VOLUMES_PATH}/nginx/ssl/ssl.crt:/etc/nginx/ssl/ssl.crt:ro
      - ${VOLUMES_PATH}/nginx/ssl/ssl.key:/etc/nginx/ssl/ssl.key:ro
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  client:
    image: modmontemplate-client:latest
    container_name: modmontemplate-client
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "49154:80"

  api:
    image: modmontemplate-api:latest
    container_name: modmontemplate-api
    build:
      context: ./backend
      dockerfile: Api/Dockerfile
    restart: unless-stopped
    ports:
      - "49155:80"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_started
    environment:
      ### Shared ###
      # Database
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      # Data Protection
      - DATA_PROTECTION_CERTIFICATE_PASSWORD
      # Email
      - EMAIL_API_KEY
      - EMAIL_FROM_ADDRESS
      # Logging
      - SEQ_HOST
      # Messaging
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - APP_BASE_ADDRESS
      ### Accounts ###
      - JWT_PRIVATE_KEY_PASSWORD
      - APP_BASE_ADDRESS
    volumes:
      ### Shared ###
      - ${VOLUMES_PATH}/backend/shared/data-protection/keys:/root/.aspnet/DataProtection-Keys
      - ${VOLUMES_PATH}/backend/shared/data-protection:/app/shared/data-protection
      - ${VOLUMES_PATH}/backend/shared/authentication:/app/shared/authentication
      ### Accounts ###
      - ${VOLUMES_PATH}/backend/accounts:/app/accounts

  db:
    image: postgres:16.1
    container_name: modmontemplate-db
    restart: unless-stopped
    ports:
      - "49156:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${VOLUMES_PATH}/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: modmontemplate-pgadmin
    restart: unless-stopped
    ports:
      - "49157:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/pgadmin:/var/lib/pgadmin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: modmontemplate-rabbitmq
    restart: unless-stopped
    ports:
      - "49158:5672"
      - "49159:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management listener [{port,15672}]
    volumes:
      - ${VOLUMES_PATH}/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  seq:
    image: datalust/seq:2024.1
    container_name: modmontemplate-seq
    restart: unless-stopped
    ports:
      - "49160:5341"
      - "49161:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_USER}
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_PASSWORD_HASH}
    volumes:
      - ${VOLUMES_PATH}/seq:/data